/*
 * KM Listas Blancas
 * Allows processing of different types of transactions
 *
 * OpenAPI spec version: 2.0.0.0
 * Contact: atencionclientes@kssoluciones.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ks.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Check
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-04T22:08:36.322Z")
public class Check {
  @SerializedName("mirc_data")
  private String mircData = null;

  @SerializedName("order_number")
  private String orderNumber = null;

  @SerializedName("contract")
  private String contract = null;

  @SerializedName("rfc")
  private String rfc = null;

  @SerializedName("customer")
  private String customer = null;

  @SerializedName("data_source")
  private String dataSource = null;

  public Check mircData(String mircData) {
    this.mircData = mircData;
    return this;
  }

   /**
   * Information related to account customer
   * @return mircData
  **/
  @ApiModelProperty(value = "Information related to account customer")
  public String getMircData() {
    return mircData;
  }

  public void setMircData(String mircData) {
    this.mircData = mircData;
  }

  public Check orderNumber(String orderNumber) {
    this.orderNumber = orderNumber;
    return this;
  }

   /**
   * Get orderNumber
   * @return orderNumber
  **/
  @ApiModelProperty(value = "")
  public String getOrderNumber() {
    return orderNumber;
  }

  public void setOrderNumber(String orderNumber) {
    this.orderNumber = orderNumber;
  }

  public Check contract(String contract) {
    this.contract = contract;
    return this;
  }

   /**
   * Get contract
   * @return contract
  **/
  @ApiModelProperty(example = "0003681", value = "")
  public String getContract() {
    return contract;
  }

  public void setContract(String contract) {
    this.contract = contract;
  }

  public Check rfc(String rfc) {
    this.rfc = rfc;
    return this;
  }

   /**
   * Get rfc
   * @return rfc
  **/
  @ApiModelProperty(example = "CIP970507CY2........", value = "")
  public String getRfc() {
    return rfc;
  }

  public void setRfc(String rfc) {
    this.rfc = rfc;
  }

  public Check customer(String customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  @ApiModelProperty(example = "000007030001338", value = "")
  public String getCustomer() {
    return customer;
  }

  public void setCustomer(String customer) {
    this.customer = customer;
  }

  public Check dataSource(String dataSource) {
    this.dataSource = dataSource;
    return this;
  }

   /**
   * Get dataSource
   * @return dataSource
  **/
  @ApiModelProperty(example = "M", value = "")
  public String getDataSource() {
    return dataSource;
  }

  public void setDataSource(String dataSource) {
    this.dataSource = dataSource;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Check check = (Check) o;
    return Objects.equals(this.mircData, check.mircData) &&
        Objects.equals(this.orderNumber, check.orderNumber) &&
        Objects.equals(this.contract, check.contract) &&
        Objects.equals(this.rfc, check.rfc) &&
        Objects.equals(this.customer, check.customer) &&
        Objects.equals(this.dataSource, check.dataSource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mircData, orderNumber, contract, rfc, customer, dataSource);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Check {\n");
    
    sb.append("    mircData: ").append(toIndentedString(mircData)).append("\n");
    sb.append("    orderNumber: ").append(toIndentedString(orderNumber)).append("\n");
    sb.append("    contract: ").append(toIndentedString(contract)).append("\n");
    sb.append("    rfc: ").append(toIndentedString(rfc)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    dataSource: ").append(toIndentedString(dataSource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

