/*
 * KM Router
 * Allows processing of different types of transactions
 *
 * OpenAPI spec version: 2.0.0.0
 * Contact: atencionclientes@kssoluciones.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ks.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Emv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-03T18:10:54.088Z")
public class Emv {
  @SerializedName("emv_5F2A")
  private String emv5F2A = null;

  @SerializedName("emv_71")
  private String emv71 = "";

  @SerializedName("emv_72")
  private String emv72 = "";

  @SerializedName("emv_82")
  private String emv82 = null;

  @SerializedName("emv_84")
  private String emv84 = null;

  @SerializedName("emv_91")
  private String emv91 = null;

  @SerializedName("emv_95")
  private String emv95 = null;

  @SerializedName("emv_9A")
  private String emv9A = null;

  @SerializedName("emv_9C")
  private String emv9C = null;

  @SerializedName("emv_5F34")
  private String emv5F34 = null;

  @SerializedName("emv_9F02")
  private String emv9F02 = null;

  @SerializedName("emv_9F03")
  private String emv9F03 = null;

  @SerializedName("emv_9F09")
  private String emv9F09 = null;

  @SerializedName("emv_9F10")
  private String emv9F10 = null;

  @SerializedName("emv_9F1A")
  private String emv9F1A = null;

  @SerializedName("emv_9F1E")
  private String emv9F1E = null;

  @SerializedName("emv_9F26")
  private String emv9F26 = null;

  @SerializedName("emv_9F27")
  private String emv9F27 = null;

  @SerializedName("emv_9F33")
  private String emv9F33 = null;

  @SerializedName("emv_9F34")
  private String emv9F34 = null;

  @SerializedName("emv_9F35")
  private String emv9F35 = null;

  @SerializedName("emv_9F36")
  private String emv9F36 = null;

  @SerializedName("emv_9F37")
  private String emv9F37 = null;

  @SerializedName("emv_9F41")
  private String emv9F41 = null;

  @SerializedName("emv_9F53")
  private String emv9F53 = null;

  @SerializedName("emv_9F5B")
  private String emv9F5B = null;

  public Emv emv5F2A(String emv5F2A) {
    this.emv5F2A = emv5F2A;
    return this;
  }

   /**
   * Transaction Currency Code
   * @return emv5F2A
  **/
  @ApiModelProperty(example = "5F2A020484", value = "Transaction Currency Code")
  public String getEmv5F2A() {
    return emv5F2A;
  }

  public void setEmv5F2A(String emv5F2A) {
    this.emv5F2A = emv5F2A;
  }

  public Emv emv71(String emv71) {
    this.emv71 = emv71;
    return this;
  }

   /**
   * Issuer Script Template
   * @return emv71
  **/
  @ApiModelProperty(value = "Issuer Script Template")
  public String getEmv71() {
    return emv71;
  }

  public void setEmv71(String emv71) {
    this.emv71 = emv71;
  }

  public Emv emv72(String emv72) {
    this.emv72 = emv72;
    return this;
  }

   /**
   * Issuer Script Template
   * @return emv72
  **/
  @ApiModelProperty(value = "Issuer Script Template")
  public String getEmv72() {
    return emv72;
  }

  public void setEmv72(String emv72) {
    this.emv72 = emv72;
  }

  public Emv emv82(String emv82) {
    this.emv82 = emv82;
    return this;
  }

   /**
   * Application Interchange Profile
   * @return emv82
  **/
  @ApiModelProperty(example = "82023900", value = "Application Interchange Profile")
  public String getEmv82() {
    return emv82;
  }

  public void setEmv82(String emv82) {
    this.emv82 = emv82;
  }

  public Emv emv84(String emv84) {
    this.emv84 = emv84;
    return this;
  }

   /**
   * Dedicated File Name
   * @return emv84
  **/
  @ApiModelProperty(example = "8400", value = "Dedicated File Name")
  public String getEmv84() {
    return emv84;
  }

  public void setEmv84(String emv84) {
    this.emv84 = emv84;
  }

  public Emv emv91(String emv91) {
    this.emv91 = emv91;
    return this;
  }

   /**
   * Issuer Authentication Data
   * @return emv91
  **/
  @ApiModelProperty(value = "Issuer Authentication Data")
  public String getEmv91() {
    return emv91;
  }

  public void setEmv91(String emv91) {
    this.emv91 = emv91;
  }

  public Emv emv95(String emv95) {
    this.emv95 = emv95;
    return this;
  }

   /**
   * Terminal Verification Result TVR
   * @return emv95
  **/
  @ApiModelProperty(example = "95050000008000", value = "Terminal Verification Result TVR")
  public String getEmv95() {
    return emv95;
  }

  public void setEmv95(String emv95) {
    this.emv95 = emv95;
  }

  public Emv emv9A(String emv9A) {
    this.emv9A = emv9A;
    return this;
  }

   /**
   * Transaction Date (AAMMDD)
   * @return emv9A
  **/
  @ApiModelProperty(example = "9A03170916", value = "Transaction Date (AAMMDD)")
  public String getEmv9A() {
    return emv9A;
  }

  public void setEmv9A(String emv9A) {
    this.emv9A = emv9A;
  }

  public Emv emv9C(String emv9C) {
    this.emv9C = emv9C;
    return this;
  }

   /**
   * Transaction Type
   * @return emv9C
  **/
  @ApiModelProperty(example = "9C0100", value = "Transaction Type")
  public String getEmv9C() {
    return emv9C;
  }

  public void setEmv9C(String emv9C) {
    this.emv9C = emv9C;
  }

  public Emv emv5F34(String emv5F34) {
    this.emv5F34 = emv5F34;
    return this;
  }

  /**
   * Aplication PAN sequence number
   * @return emv5F34
   **/
  @ApiModelProperty(example = "00", value = "Aplication PAN sequence number")
  public String getEmv5F34() {
    return emv5F34;
  }

  public void setEmv5F34(String emv5F34) {
    this.emv5F34 = emv5F34;
  }

  public Emv emv9F02(String emv9F02) {
    this.emv9F02 = emv9F02;
    return this;
  }

   /**
   * Transaction Amount
   * @return emv9F02
  **/
  @ApiModelProperty(example = "9F0206000000065989", value = "Transaction Amount")
  public String getEmv9F02() {
    return emv9F02;
  }

  public void setEmv9F02(String emv9F02) {
    this.emv9F02 = emv9F02;
  }

  public Emv emv9F03(String emv9F03) {
    this.emv9F03 = emv9F03;
    return this;
  }

   /**
   * Amount Other
   * @return emv9F03
  **/
  @ApiModelProperty(example = "9F0306000000000000", value = "Amount Other")
  public String getEmv9F03() {
    return emv9F03;
  }

  public void setEmv9F03(String emv9F03) {
    this.emv9F03 = emv9F03;
  }

  public Emv emv9F09(String emv9F09) {
    this.emv9F09 = emv9F09;
    return this;
  }

   /**
   * Application Version Number
   * @return emv9F09
  **/
  @ApiModelProperty(example = "9F09020002", value = "Application Version Number")
  public String getEmv9F09() {
    return emv9F09;
  }

  public void setEmv9F09(String emv9F09) {
    this.emv9F09 = emv9F09;
  }

  public Emv emv9F10(String emv9F10) {
    this.emv9F10 = emv9F10;
    return this;
  }

   /**
   * Issuer Application Data
   * @return emv9F10
  **/
  @ApiModelProperty(example = "9F10120310A0400522000000000000", value = "Issuer Application Data")
  public String getEmv9F10() {
    return emv9F10;
  }

  public void setEmv9F10(String emv9F10) {
    this.emv9F10 = emv9F10;
  }

  public Emv emv9F1A(String emv9F1A) {
    this.emv9F1A = emv9F1A;
    return this;
  }

   /**
   * Terminal Country Code
   * @return emv9F1A
  **/
  @ApiModelProperty(example = "9F1A020484", value = "Terminal Country Code")
  public String getEmv9F1A() {
    return emv9F1A;
  }

  public void setEmv9F1A(String emv9F1A) {
    this.emv9F1A = emv9F1A;
  }

  public Emv emv9F1E(String emv9F1E) {
    this.emv9F1E = emv9F1E;
    return this;
  }

   /**
   * Interface Device (IFD) Srl Nmbr
   * @return emv9F1E
  **/
  @ApiModelProperty(example = "9F1E083831323737343636", value = "Interface Device (IFD) Srl Nmbr")
  public String getEmv9F1E() {
    return emv9F1E;
  }

  public void setEmv9F1E(String emv9F1E) {
    this.emv9F1E = emv9F1E;
  }

  public Emv emv9F26(String emv9F26) {
    this.emv9F26 = emv9F26;
    return this;
  }

   /**
   * Application Cryptogram (AC)
   * @return emv9F26
  **/
  @ApiModelProperty(example = "9F26088217586D177C320A", value = "Application Cryptogram (AC)")
  public String getEmv9F26() {
    return emv9F26;
  }

  public void setEmv9F26(String emv9F26) {
    this.emv9F26 = emv9F26;
  }

  public Emv emv9F27(String emv9F27) {
    this.emv9F27 = emv9F27;
    return this;
  }

   /**
   * Cryptogram Information Data
   * @return emv9F27
  **/
  @ApiModelProperty(example = "9F270180", value = "Cryptogram Information Data")
  public String getEmv9F27() {
    return emv9F27;
  }

  public void setEmv9F27(String emv9F27) {
    this.emv9F27 = emv9F27;
  }

  public Emv emv9F33(String emv9F33) {
    this.emv9F33 = emv9F33;
    return this;
  }

   /**
   * Terminal Capabilities
   * @return emv9F33
  **/
  @ApiModelProperty(example = "9F3303E0B0C8", value = "Terminal Capabilities")
  public String getEmv9F33() {
    return emv9F33;
  }

  public void setEmv9F33(String emv9F33) {
    this.emv9F33 = emv9F33;
  }

  public Emv emv9F34(String emv9F34) {
    this.emv9F34 = emv9F34;
    return this;
  }

   /**
   * Crdhldr Verific Mthd (CVM) Rslts
   * @return emv9F34
  **/
  @ApiModelProperty(example = "9F34031E0300", value = "Crdhldr Verific Mthd (CVM) Rslts")
  public String getEmv9F34() {
    return emv9F34;
  }

  public void setEmv9F34(String emv9F34) {
    this.emv9F34 = emv9F34;
  }

  public Emv emv9F35(String emv9F35) {
    this.emv9F35 = emv9F35;
    return this;
  }

   /**
   * Terminal Type
   * @return emv9F35
  **/
  @ApiModelProperty(example = "9F350122", value = "Terminal Type")
  public String getEmv9F35() {
    return emv9F35;
  }

  public void setEmv9F35(String emv9F35) {
    this.emv9F35 = emv9F35;
  }

  public Emv emv9F36(String emv9F36) {
    this.emv9F36 = emv9F36;
    return this;
  }

   /**
   * Application Transaction Counter
   * @return emv9F36
  **/
  @ApiModelProperty(example = "9F36020015", value = "Application Transaction Counter")
  public String getEmv9F36() {
    return emv9F36;
  }

  public void setEmv9F36(String emv9F36) {
    this.emv9F36 = emv9F36;
  }

  public Emv emv9F37(String emv9F37) {
    this.emv9F37 = emv9F37;
    return this;
  }

   /**
   * Unpredictable Number
   * @return emv9F37
  **/
  @ApiModelProperty(example = "9F370401DB603D", value = "Unpredictable Number")
  public String getEmv9F37() {
    return emv9F37;
  }

  public void setEmv9F37(String emv9F37) {
    this.emv9F37 = emv9F37;
  }

  public Emv emv9F41(String emv9F41) {
    this.emv9F41 = emv9F41;
    return this;
  }

   /**
   * Transaction Sequence Counter
   * @return emv9F41
  **/
  @ApiModelProperty(example = "9F410400095101", value = "Transaction Sequence Counter")
  public String getEmv9F41() {
    return emv9F41;
  }

  public void setEmv9F41(String emv9F41) {
    this.emv9F41 = emv9F41;
  }

  public Emv emv9F53(String emv9F53) {
    this.emv9F53 = emv9F53;
    return this;
  }

   /**
   * Transaction Category Code
   * @return emv9F53
  **/
  @ApiModelProperty(example = "9F530152", value = "Transaction Category Code")
  public String getEmv9F53() {
    return emv9F53;
  }

  public void setEmv9F53(String emv9F53) {
    this.emv9F53 = emv9F53;
  }

  public Emv emv9F5B(String emv9F5B) {
    this.emv9F5B = emv9F5B;
    return this;
  }

   /**
   * Issuer Script Result
   * @return emv9F5B
  **/
  @ApiModelProperty(value = "Issuer Script Result")
  public String getEmv9F5B() {
    return emv9F5B;
  }

  public void setEmv9F5B(String emv9F5B) {
    this.emv9F5B = emv9F5B;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Emv emv = (Emv) o;
    return Objects.equals(this.emv5F2A, emv.emv5F2A) &&
        Objects.equals(this.emv71, emv.emv71) &&
        Objects.equals(this.emv72, emv.emv72) &&
        Objects.equals(this.emv82, emv.emv82) &&
        Objects.equals(this.emv84, emv.emv84) &&
        Objects.equals(this.emv91, emv.emv91) &&
        Objects.equals(this.emv95, emv.emv95) &&
        Objects.equals(this.emv9A, emv.emv9A) &&
        Objects.equals(this.emv9C, emv.emv9C) &&
        Objects.equals(this.emv5F34, emv.emv5F34) &&
        Objects.equals(this.emv9F02, emv.emv9F02) &&
        Objects.equals(this.emv9F03, emv.emv9F03) &&
        Objects.equals(this.emv9F09, emv.emv9F09) &&
        Objects.equals(this.emv9F10, emv.emv9F10) &&
        Objects.equals(this.emv9F1A, emv.emv9F1A) &&
        Objects.equals(this.emv9F1E, emv.emv9F1E) &&
        Objects.equals(this.emv9F26, emv.emv9F26) &&
        Objects.equals(this.emv9F27, emv.emv9F27) &&
        Objects.equals(this.emv9F33, emv.emv9F33) &&
        Objects.equals(this.emv9F34, emv.emv9F34) &&
        Objects.equals(this.emv9F35, emv.emv9F35) &&
        Objects.equals(this.emv9F36, emv.emv9F36) &&
        Objects.equals(this.emv9F37, emv.emv9F37) &&
        Objects.equals(this.emv9F41, emv.emv9F41) &&
        Objects.equals(this.emv9F53, emv.emv9F53) &&
        Objects.equals(this.emv9F5B, emv.emv9F5B);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emv5F2A, emv71, emv72, emv82, emv84, emv91, emv95, emv9A, emv9C,emv5F34, emv9F02, emv9F03, emv9F09, emv9F10, emv9F1A, emv9F1E, emv9F26, emv9F27, emv9F33, emv9F34, emv9F35, emv9F36, emv9F37, emv9F41, emv9F53, emv9F5B);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Emv {\n");

    sb.append("    emv5F2A: ").append(toIndentedString(emv5F2A)).append("\n");
    sb.append("    emv71: ").append(toIndentedString(emv71)).append("\n");
    sb.append("    emv72: ").append(toIndentedString(emv72)).append("\n");
    sb.append("    emv82: ").append(toIndentedString(emv82)).append("\n");
    sb.append("    emv84: ").append(toIndentedString(emv84)).append("\n");
    sb.append("    emv91: ").append(toIndentedString(emv91)).append("\n");
    sb.append("    emv95: ").append(toIndentedString(emv95)).append("\n");
    sb.append("    emv9A: ").append(toIndentedString(emv9A)).append("\n");
    sb.append("    emv9C: ").append(toIndentedString(emv9C)).append("\n");
    sb.append("    emv5F34: ").append(toIndentedString(emv5F34)).append("\n");
    sb.append("    emv9F02: ").append(toIndentedString(emv9F02)).append("\n");
    sb.append("    emv9F03: ").append(toIndentedString(emv9F03)).append("\n");
    sb.append("    emv9F09: ").append(toIndentedString(emv9F09)).append("\n");
    sb.append("    emv9F10: ").append(toIndentedString(emv9F10)).append("\n");
    sb.append("    emv9F1A: ").append(toIndentedString(emv9F1A)).append("\n");
    sb.append("    emv9F1E: ").append(toIndentedString(emv9F1E)).append("\n");
    sb.append("    emv9F26: ").append(toIndentedString(emv9F26)).append("\n");
    sb.append("    emv9F27: ").append(toIndentedString(emv9F27)).append("\n");
    sb.append("    emv9F33: ").append(toIndentedString(emv9F33)).append("\n");
    sb.append("    emv9F34: ").append(toIndentedString(emv9F34)).append("\n");
    sb.append("    emv9F35: ").append(toIndentedString(emv9F35)).append("\n");
    sb.append("    emv9F36: ").append(toIndentedString(emv9F36)).append("\n");
    sb.append("    emv9F37: ").append(toIndentedString(emv9F37)).append("\n");
    sb.append("    emv9F41: ").append(toIndentedString(emv9F41)).append("\n");
    sb.append("    emv9F53: ").append(toIndentedString(emv9F53)).append("\n");
    sb.append("    emv9F5B: ").append(toIndentedString(emv9F5B)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

