/*
 * KM Router LEALTAD
 * Allows processing of different types of transactions
 *
 * OpenAPI spec version: 2.2.0.2
 * Contact: atencionclientes@kssoluciones.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ks.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * GiftCard
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-04T21:31:34.171Z")
public class GiftCard {
  @SerializedName("casher_id")
  private String casherId = null;

  @SerializedName("redention_type")
  private String redentionType = null;

  @SerializedName("verification_code")
  private String verificationCode = null;

  public GiftCard casherId(String casherId) {
    this.casherId = casherId;
    return this;
  }

   /**
   * Get casherId
   * @return casherId
  **/
  @ApiModelProperty(value = "")
  public String getCasherId() {
    return casherId;
  }

  public void setCasherId(String casherId) {
    this.casherId = casherId;
  }

  public GiftCard redentionType(String redentionType) {
    this.redentionType = redentionType;
    return this;
  }

   /**
   * Get redentionType
   * @return redentionType
  **/
  @ApiModelProperty(value = "")
  public String getRedentionType() {
    return redentionType;
  }

  public void setRedentionType(String redentionType) {
    this.redentionType = redentionType;
  }

  public GiftCard verificationCode(String verificationCode) {
    this.verificationCode = verificationCode;
    return this;
  }

   /**
   * Get verificationCode
   * @return verificationCode
  **/
  @ApiModelProperty(value = "")
  public String getVerificationCode() {
    return verificationCode;
  }

  public void setVerificationCode(String verificationCode) {
    this.verificationCode = verificationCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GiftCard giftCard = (GiftCard) o;
    return Objects.equals(this.casherId, giftCard.casherId) &&
        Objects.equals(this.redentionType, giftCard.redentionType) &&
        Objects.equals(this.verificationCode, giftCard.verificationCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(casherId, redentionType, verificationCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GiftCard {\n");
    
    sb.append("    casherId: ").append(toIndentedString(casherId)).append("\n");
    sb.append("    redentionType: ").append(toIndentedString(redentionType)).append("\n");
    sb.append("    verificationCode: ").append(toIndentedString(verificationCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

