/*
 * KM Router
 * Allows processing of different types of transactions
 *
 * OpenAPI spec version: 2.0.0.0
 * Contact: atencionclientes@kssoluciones.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ks.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Points
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-03T18:10:54.088Z")
public class Points
{
    @SerializedName("redeemed_amount")
    private String redeemedAmount = null;

    @SerializedName("redeemed_points")
    private String redeemedPoints = null;

    @SerializedName("point_exponential_factor")
    private String pointExponentialFactor = null;

    @SerializedName("available_balance")
    private String availableBalance = null;

    @SerializedName("prev_points_balance")
    private String prevPointsBalance = null;

    @SerializedName("prev_balance")
    private String prevBalance = null;

    @SerializedName("exp_points_expiration")
    private String expPointsExpiration = null;

    @SerializedName("reedemed_exp_amount")
    private String reedemedExpAmount = null;

    @SerializedName("reedemed_exp_points")
    private String reedemedExpPoints = null;

    @SerializedName("available_exp_balance")
    private String availableExpBalance = null;

    @SerializedName("available_exp_points")
    private String availableExpPoints = null;

    @SerializedName("existing_client")
    private String existingClient = null;

    public Points redeemedAmount(String redeemedAmount)
    {
        this.redeemedAmount = redeemedAmount;
        return this;
    }

    /**
     * Get redeemedAmount
     *
     * @return redeemedAmount
     **/
    @ApiModelProperty(example = "550.0", value = "")
    public String getRedeemedAmount()
    {
        return redeemedAmount;
    }

    public void setRedeemedAmount(String redeemedAmount)
    {
        this.redeemedAmount = redeemedAmount;
    }

    public Points redeemedPoints(String redeemedPoints)
    {
        this.redeemedPoints = redeemedPoints;
        return this;
    }

    /**
     * Get redeemedPoints
     *
     * @return redeemedPoints
     **/
    @ApiModelProperty(example = "550.0", value = "")
    public String getRedeemedPoints()
    {
        return redeemedPoints;
    }

    public void setRedeemedPoints(String redeemedPoints)
    {
        this.redeemedPoints = redeemedPoints;
    }

    public Points pointExponentialFactor(String pointExponentialFactor)
    {
        this.pointExponentialFactor = pointExponentialFactor;
        return this;
    }

    /**
     * Get pointExponentialFactor
     *
     * @return pointExponentialFactor
     **/
    @ApiModelProperty(example = "1.0", value = "")
    public String getPointExponentialFactor()
    {
        return pointExponentialFactor;
    }

    public void setPointExponentialFactor(String pointExponentialFactor)
    {
        this.pointExponentialFactor = pointExponentialFactor;
    }

    public Points availableBalance(String availableBalance)
    {
        this.availableBalance = availableBalance;
        return this;
    }

    /**
     * Get availableBalance
     *
     * @return availableBalance
     **/
    @ApiModelProperty(example = "0.0", value = "")
    public String getAvailableBalance()
    {
        return availableBalance;
    }

    public void setAvailableBalance(String availableBalance)
    {
        this.availableBalance = availableBalance;
    }

    public Points prevPointsBalance(String prevPointsBalance)
    {
        this.prevPointsBalance = prevPointsBalance;
        return this;
    }

    /**
     * Get prevPointsBalance
     *
     * @return prevPointsBalance
     **/
    @ApiModelProperty(example = "0.0", value = "")
    public String getPrevPointsBalance()
    {
        return prevPointsBalance;
    }

    public void setPrevPointsBalance(String prevPointsBalance)
    {
        this.prevPointsBalance = prevPointsBalance;
    }

    public Points prevBalance(String prevBalance)
    {
        this.prevBalance = prevBalance;
        return this;
    }

    /**
     * Get prevBalance
     *
     * @return prevBalance
     **/
    @ApiModelProperty(example = "0.0", value = "")
    public String getPrevBalance()
    {
        return prevBalance;
    }

    public void setPrevBalance(String prevBalance)
    {
        this.prevBalance = prevBalance;
    }

    public Points expPointsExpiration(String expPointsExpiration)
    {
        this.expPointsExpiration = expPointsExpiration;
        return this;
    }

    /**
     * Get expPointsExpiration
     *
     * @return expPointsExpiration
     **/
    @ApiModelProperty(value = "")
    public String getExpPointsExpiration()
    {
        return expPointsExpiration;
    }

    public void setExpPointsExpiration(String expPointsExpiration)
    {
        this.expPointsExpiration = expPointsExpiration;
    }

    public Points reedemedExpAmount(String reedemedExpAmount)
    {
        this.reedemedExpAmount = reedemedExpAmount;
        return this;
    }

    /**
     * Get reedemedExpAmount
     *
     * @return reedemedExpAmount
     **/
    @ApiModelProperty(value = "")
    public String getReedemedExpAmount()
    {
        return reedemedExpAmount;
    }

    public void setReedemedExpAmount(String reedemedExpAmount)
    {
        this.reedemedExpAmount = reedemedExpAmount;
    }

    public Points reedemedExpPoints(String reedemedExpPoints)
    {
        this.reedemedExpPoints = reedemedExpPoints;
        return this;
    }

    /**
     * Get reedemedExpPoints
     *
     * @return reedemedExpPoints
     **/
    @ApiModelProperty(value = "")
    public String getReedemedExpPoints()
    {
        return reedemedExpPoints;
    }

    public void setReedemedExpPoints(String reedemedExpPoints)
    {
        this.reedemedExpPoints = reedemedExpPoints;
    }

    public Points availableExpBalance(String availableExpBalance)
    {
        this.availableExpBalance = availableExpBalance;
        return this;
    }

    /**
     * Get availableExpBalance
     *
     * @return availableExpBalance
     **/
    @ApiModelProperty(value = "")
    public String getAvailableExpBalance()
    {
        return availableExpBalance;
    }

    public void setAvailableExpBalance(String availableExpBalance)
    {
        this.availableExpBalance = availableExpBalance;
    }

    public Points availableExpPoints(String availableExpPoints)
    {
        this.availableExpPoints = availableExpPoints;
        return this;
    }

    /**
     * Get availableExpPoints
     *
     * @return availableExpPoints
     **/
    @ApiModelProperty(value = "")
    public String getAvailableExpPoints()
    {
        return availableExpPoints;
    }

    public void setAvailableExpPoints(String availableExpPoints)
    {
        this.availableExpPoints = availableExpPoints;
    }

    public Points existingClient(String existingClient)
    {
        this.existingClient = existingClient;
        return this;
    }

    /**
     * Get existingClient
     *
     * @return existingClient
     **/
    @ApiModelProperty(example = "00", value = "")
    public String getExistingClient()
    {
        return existingClient;
    }

    public void setExistingClient(String existingClient)
    {
        this.existingClient = existingClient;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        Points points = (Points) o;
        return Objects.equals(this.redeemedAmount, points.redeemedAmount) && Objects.equals(this.redeemedPoints, points.redeemedPoints) && Objects.equals(this.pointExponentialFactor, points.pointExponentialFactor) && Objects.equals(this.availableBalance, points.availableBalance) && Objects.equals(this.prevPointsBalance, points.prevPointsBalance) && Objects.equals(this.prevBalance, points.prevBalance) && Objects.equals(this.expPointsExpiration, points.expPointsExpiration) && Objects.equals(this.reedemedExpAmount, points.reedemedExpAmount) && Objects.equals(this.reedemedExpPoints, points.reedemedExpPoints) && Objects.equals(this.availableExpBalance, points.availableExpBalance) && Objects.equals(this.availableExpPoints, points.availableExpPoints) && Objects.equals(this.existingClient, points.existingClient);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(redeemedAmount, redeemedPoints, pointExponentialFactor, availableBalance, prevPointsBalance, prevBalance, expPointsExpiration, reedemedExpAmount, reedemedExpPoints, availableExpBalance, availableExpPoints, existingClient);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class Points {\n");

        sb.append("    redeemedAmount: ").append(toIndentedString(redeemedAmount)).append("\n");
        sb.append("    redeemedPoints: ").append(toIndentedString(redeemedPoints)).append("\n");
        sb.append("    pointExponentialFactor: ").append(toIndentedString(pointExponentialFactor)).append("\n");
        sb.append("    availableBalance: ").append(toIndentedString(availableBalance)).append("\n");
        sb.append("    prevPointsBalance: ").append(toIndentedString(prevPointsBalance)).append("\n");
        sb.append("    prevBalance: ").append(toIndentedString(prevBalance)).append("\n");
        sb.append("    expPointsExpiration: ").append(toIndentedString(expPointsExpiration)).append("\n");
        sb.append("    reedemedExpAmount: ").append(toIndentedString(reedemedExpAmount)).append("\n");
        sb.append("    reedemedExpPoints: ").append(toIndentedString(reedemedExpPoints)).append("\n");
        sb.append("    availableExpBalance: ").append(toIndentedString(availableExpBalance)).append("\n");
        sb.append("    availableExpPoints: ").append(toIndentedString(availableExpPoints)).append("\n");
        sb.append("    existingClient: ").append(toIndentedString(existingClient)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

