/*
 * KM XReference
 * Allows processing of different types of transactions
 *
 * OpenAPI spec version: 3.0.0.0
 * Contact: atencionclientes@kssoluciones.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ks.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * XReference
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-13T21:58:48.570Z")
public class XReference
{
    @SerializedName("xreference")
    private String xReference = null;

    @SerializedName("card_number")
    private String cardNumber = null;

    public XReference xReference(String xReference)
    {
        this.xReference = xReference;
        return this;
    }

    /**
     * XReference
     *
     * @return xReference
     **/
    @ApiModelProperty(example = "4444555566667777888", value = "xreference")
    public String getXReference()
    {
        return xReference;
    }

    public void setXReference(String xReference)
    {
        this.xReference = xReference;
    }

    public XReference cardNumber(String cardNumber)
    {
        this.cardNumber = cardNumber;
        return this;
    }

    /**
     * XReference
     *
     * @return cardNumber
     **/
    @ApiModelProperty(example = "4444555666777888", value = "card_number")
    public String getCardNumber()
    {
        return cardNumber;
    }

    public void setCardNumber(String cardNumber)
    {
        this.cardNumber = cardNumber;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        XReference xreference = (XReference) o;
        return Objects.equals(this.xReference, xreference.xReference) && Objects.equals(this.cardNumber, xreference.cardNumber);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(xReference, cardNumber);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class XReference {\n");

        sb.append("    xreference: ").append(toIndentedString(xReference)).append("\n");
        sb.append("    card_number: ").append(toIndentedString(cardNumber)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public String toSingleMaskString()
    {
        return toMaskaredString().replace("\n", "  ");
    }

    public String toSingleLineString()
    {
        return this.toString().replace("\n", "  ");
    }

    public String toMaskaredString()
    {
        final String cardNumber = this.cardNumber.toString();
        final int length = cardNumber.length();
        final String maskedCard = cardNumber.substring(0, 6) + refill("*", length - 10) + cardNumber.substring(length - 4);

        return this.toSingleLineString().replace(cardNumber, maskedCard);
    }

    public static String refill(String character, int length)
    {
        final StringBuilder refill = new StringBuilder();

        for (int i = 0; i < length; i++)
        {
            refill.append(character);
        }
        return refill.toString();
    }
}

